### ISSUE TITLE
Infografia evelyn santiago

### ISSUE THREAD

**Issue by evelyn-santiago** [SistemasTecTlaxiaco/infografia-de-hilos-evelyn-santiago#2]
[Hilos infografia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-evelyn-santiago/files/15099110/Hilos.infografia.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Hola buenas tardes compañera, bien hecho, 20 de 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
